### PR TITLE
Update depedency versions

### PR DESCRIPTION
**Pull request by willnode**
This is a PR that fixes CI build, also updating many depedency versions.

There's something need to be aware before we able to build this project:
+ There's unfinished "jasmine" grunt task that I don't know what it does but sure it's essential for building the app
+ You need to use (https://github.com/adobe/brackets-shell) in order to build, but I have difficulties doing it myself because my environment is Windows
+ Because of that, I can't guarantee that my changes won't broke something else. I haven't got time to build & test myself.
+ We need to setup a proper server for the app watching software updates (check `src/brackets.config.dist.json`)

### CODE REVIEW

**Comment by willnode** [comment]
And sidenote: I think we have to [migrate away](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works) from Travis CI and start using Github Actions.

**Comment by yogo1212** [comment]
@willnode i agree about the CI switch. the current process is unnecessarily complex.

let me try to get docker up to run test the build..

**Comment by yogo1212** [comment]
pew. i'm having trouble getting brackets-shell to run....

**Comment by yogo1212** [comment]
is there someone who is technically apt to review and finish this?

**Comment by willnode** [comment]
Wow, I almost forgot this PR exists. I'll try rebuilding it this weekend.

**Review by rileyhawk1417 — COMMENTED** [review]
Dev environment runs on linux. I guess windows is next.

**Review by LehanMusthafa — APPROVED** [review]

**Review by ScanuNicco — APPROVED** [review]

**Review by rileyhawk1417 — APPROVED** [review]

**Comment by yogo1212** [comment]
huh?
i don't understand why merging is still blocked with three reviews..

**Review by yogo1212 — APPROVED** [review]

**Pull request merged**
