### PR TITLE
Fix typo in FindInFiles-test.js

### PR DESCRIPTION
**Pull request by eltociear**
occurences -> occurrences

### CODE REVIEW

**Comment by brackets-io** [comment]
### Error: Contributor Licence Agreement Signature Missing
Please sign the Contributor Licence Agreement by clicking the following link.
<p align="center"> <a href="https://brackets.io/contributor-license-agreement/">Click here to sign the CLA</a></p>
### Error: Contributor Licence Agreement Signature Missing
The following commiter(s) has not signed the Contributor Licence Agreement:
eltociear
Please sign the Contributor Licence Agreement by clicking the following link. 
<p align="center"> <a href="https://brackets.io/contributor-license-agreement/">Click here to sign the CLA</a></p>

**Comment by eltociear** [comment]
I signed CLA.

**Comment by brackets-io** [comment]
## Thank You for making this pull request.

**Review by abose — APPROVED** [review]

**Comment by abose** [comment]
Thanks @eltociear for contributing.
LGTM. Merging.

**Pull request merged**
